### ISSUE TITLE
format of power-spectrum.

### ISSUE THREAD

**Issue by rainwoodman** [junkoda/cola_halo#1]
The format of camb0_matterpower.dat seems to be undocumented.

Looks like the expected format is 
`# k [Mpc/h] P`

**Comment by junkoda** [comment]
Sorry, I haven't realised this message. Yes, the unit is k [Mpc/h] P. You can use the matterpower.dat output of CAMB. I am trying to document it before I publish a paper on this.

**Comment by rainwoodman** [comment]
Thanks. 

Please notice we (an undergrad and me) have been working on the cola_halo code base at
http://github.com/rainwoodman/cola_halo

Some additions are:
- fixing the pure pm mode
- variable pm mesh size
- high order diff kernels and discrete poisson solver kernel
- loga/arbitrary stepping

We also want to migrate to pencil fft with PFFT (github.com/mpip/pfft), because running nc=2048 **3  on 2048 cores the surface to volume ratio of slab domains is too big, and switching to pencils may run faster.

**Comment by junkoda** [comment]
Wonderful!
Yes, using the simple slab decomposition was a serious limitation of my
parallelisation.

cheers,
Jun
